name: code-quality

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '22'
      - name: Run spotless check
        run: mvn spotless:check
